### ISSUE TITLE
Plugin not found (Gradle 6.0.1)

### ISSUE THREAD

**Issue by sergio11** [moberwasserlechner/jasypt-gradle-plugin#1]
Hello!! How are you?. I need to incorporate Jasypt in my Spring Boot project to secure certain keys and credentials from external services, the problem that it does not have support to encrypt values ​​with Gradles tasks, that's why I have been interested in your repository.

My Spring Boot project uses Gradle 6.0.1, I have incorporated its plugin as follows:

![image](https://user-images.githubusercontent.com/6996211/77693473-b16b2780-6fa8-11ea-8800-3890edba273e.png)

Also I have enabled JCenter as a repository for searching plugins as follows

![image](https://user-images.githubusercontent.com/6996211/77693863-5980f080-6fa9-11ea-8ea5-5dc6f1bb04ab.png)
But I have not managed to solve your plugin, I have the following message

![image](https://user-images.githubusercontent.com/6996211/77693942-81705400-6fa9-11ea-8518-fa4e74aedca3.png)

Could you tell me how I can incorporate your plugin into my project or some way to encrypt data with gradle using Jasypt.? Thank you very much for your time. Greetings

**Comment by moberwasserlechner** [comment]
Hi,

I have clearified the README's usage section. See https://github.com/moberwasserlechner/jasypt-gradle-plugin#usage

The following is the top of a Spring Boot service build by Gradle 6.1.1. 

```
buildscript {
	repositories {
		jcenter()
	}
	dependencies {
		classpath "com.byteowls:jasypt-gradle-plugin:1.0.1"
	}
}

plugins {
	id 'java'
	id 'org.springframework.boot' version '2.2.6.RELEASE'
	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
}

apply plugin: "com.byteowls.jasypt"
```
If I run `./gradlew tasks` the plugin is successfully discovered.
![grafik](https://user-images.githubusercontent.com/1049938/77704761-1a10cf00-6fbe-11ea-85c5-08c283e4dde0.png)

Right now this workaround is all I can offer as I currently don't have the time to investigate why the plugin is not discovered when used in the `plugin` block. I created a task #2 but can't present a timeline.

BR, Michael
